# Generated by Django 3.1.7 on 2021-03-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source1', models.TextField()),
                ('source2', models.TextField()),
                ('target1', models.TextField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=3)),
                ('target2', models.TextField()),
                ('unit', models.TextField(default='what up!')),
            ],
        ),
    ]
