# Generated by Django 3.1.7 on 2021-03-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplychain',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
